#pragma once
#define TAM 100
#define MAX_CARS 10
#define MAX_FROGS 10
#define MAX_ROWS 10
#define MAX_COLS 20

#define TAM_BUFFER_CIRCULAR 10

#define SEMAPHORE_UNIQUE_SERVER TEXT("SEM_UNIQUE_SERVE")

#define FILE_MAPPING_GAME_DATA TEXT("FILE_MAPPING_GAME_DATA")

#define SHARED_MEMORIE_EVENT TEXT("SHARED_MEMORIE_EVENT")

#define SHARED_MEMORIE_MUTEX TEXT("SHARED_MEMORIE_MUTEX")
